@listId=dd2aac79-af58-4821-8b02-352632d34615

POST {{BASE_URL}}/lists/{{listId}}/items
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
    "listId": "{{listId}}",
    "name": "new item"
}