name: Frontend CI

on:
  pull_request:
    branches: ['main']

env:
  APP_PATH: './frontend/app'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{APP_PATH}}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version-file: '${{APP_PATH}}/.nvmrc'
    - name: Install dependencies
      run: npm ci
    - name: Formatting
      run: npm run format:check
    - name: Linting
      run: npm run lint:check
    - name: Build
      run: npm run build